### ISSUE TITLE
explication

### ISSUE THREAD

**Issue by selmi-karim** [satoripop/thesuperlogger#1]
What are the reasons to use 'return function' in levelFromStatus function.
if you don't have private methods or variables that you want to protect.
Thanks.

```
module.exports.levelFromStatus = () =>{
	return (req, res) => {
		var level = '';
		if (res.statusCode >= 100) {
			level = 'debug';
		}
		if (res.statusCode >= 400) {
			level = 'warning';
		}
		if (res.statusCode >= 500) {
			level = 'error';
		}
		return level;
	};
};

```

**Comment by ImenAmmar** [comment]
At first, I needed levelFromStatus to return a function as a middleware (that I could pass the request and response). My needs changed while coding. Not going to lie, now that you say it, I should have changed it to make it simpler like this:
```
module.exports.levelFromStatus = (res) =>{
        var level = '';
	if (res.statusCode >= 100) {
		level = 'debug';
	}
	if (res.statusCode >= 400) {
		level = 'warning';
	}
	if (res.statusCode >= 500) {
		level = 'error';
	}
	return level;
};
```
I will close this thread, once I would have made the changes.
